### ISSUE TITLE
[Docs] The feature guide is incomplete

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-indent#9]
Missing/things to do:

* [ ] The name of the guide. Is it really about "block indentation"? Shouldn't it be "text indentation" instead? 
    * Not sure people think about lists as blocks.
    * We'd need to explain what is block and what is not here.
* [ ] Intro:
    * [ ] What does this feature actually offer?
    * [ ] Explanation what is `Indent` what is `IndentBlock` and what's the role of the `List` plugin in all of this.
* [ ] A few words of explanation before the demo.
* [ ] Refactoring in "Indenting list". Some clarification about `Indent` vs `List` should be in the intro.
* [ ] How to implement own feature that plugs into the indentation system (`MyIndentWhatever` section)?
* [ ] Common API clean-up (language, mostly). 

cc @Reinmar

**Comment by thiberaw** [comment]
Plus link to API is broken
[@ckeditor/ckeditor5-indent package](https://ckeditor.com/docs/ckeditor5/latest/api/indent.html)

![image](https://user-images.githubusercontent.com/5416065/60672008-e7d5a500-9e63-11e9-97cf-155963884ad2.png)

**Comment by Reinmar** [comment]
> The name of the guide. Is it really about "block indentation"? Shouldn't it be "text indentation" instead?

![image](https://user-images.githubusercontent.com/156149/60672548-f4fb8f80-9e75-11e9-8d5e-265356089d9a.png)

And, text indentation feels more like first line indentation to me. 

So, I think "block indentation" is fine. It's also what CKEditor 4 uses.

---



> * [ ]  Explanation what is `Indent` what is `IndentBlock` and what's the role of the `List` plugin in all of this.
> *

This is actually explained there ;)

![image](https://user-images.githubusercontent.com/156149/60672852-badebd80-9e76-11e9-935b-fb4dcb1524e9.png)

---

>  Refactoring in "Indenting list". Some clarification about Indent vs List should be in the intro.

Why? This guide sells block indentation (block = paragraphs, headings, etc.). This was its main job. I intentionally left lists aside because it doesn't seem confusing right now whether we support that or not.

--- 

>  A few words of explanation before the demo.

What's wrong with the current text?

> The indentation feature allows to set indentation of text blocks like paragraphs or headings and lists.

**Comment by Reinmar** [comment]
> Plus link to API is broken

The new docs weren't published yet. We've just tagged the release today and the docs will be published in 1-2h.

**Comment by mlewand** [comment]
Gents, while discussing this issue let's not forget one thing: let's keep in mind that it is likely

**Comment by mlewand** [comment]
As far as the name goes, the more I think it the more "block indentation" make sense to me **for this** particular feature.

**Comment by Reinmar** [comment]
Assigning to @AnnaTomanek if she wants to propose and make some changes. If not, off to `backlog`.

**Comment by AnnaTomanek** [comment]
I'd say it's fine for now after the recent fine-tuning. We're missing the part with custom indentation, but maybe let's wait and see if there is any interest in that.
